export const replaceAccents = (str) => `LOWER(REPLACE(REPLACE(REPLACE(REPLACE(
  REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
  REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
  ${str},
  'é', 'e'),
  'è', 'e'),
  'ê', 'e'),
  'ë', 'e'),
  'â', 'a'),
  'ä', 'a'),
  'î', 'i'),
  'ï', 'i'),
  'ö', 'o'),
  'û', 'u'),
  'ü', 'u'),
  'É', 'E'),
  'È', 'E'),
  'Ê', 'E'),
  'Ë', 'E'),
  'Â', 'A'),
  'Ä', 'A'),
  'Î', 'I'),
  'Ï', 'I'),
  'Ö', 'O'),
  'Û', 'U'),
  'Ü', 'U'),
  '-', ''),
  '''', ''))`
